### ISSUE TITLE
Websocket 503 Errors (Negotiate Unknown)

### ISSUE THREAD

**Issue by luckylwk** [bitfinexcom/bitfinex-api-node#162]
I implemented the websocket with API keys and it all worked perfectly for a few weeks. Since yesterday evening I start getting back the following error:

```
Error Message:  Negotiate Unknown
Exception:  undefined
Error Data:  503
```

Is anybody experiencing the same thing?

---

Note, the public websockets seem to be working fine:

```
const WebSocket = require('ws')

const wss = new WebSocket('wss://api.bitfinex.com/ws/2')

wss.onmessage = (msg) => console.log(msg.data)
wss.onopen = () => {
    wss.send( JSON.stringify({"event":"subscribe", "channel":"ticker", "pair":"BTCUSD"}) )
}
```

**Comment by f3rno** [comment]
Hmm, this could be due to the DDoS; how often is it happening?

**Comment by amlwwalker** [comment]
Im getting this too. I have seen it now for about 3 days, each time I start the connection.

**Comment by amlwwalker** [comment]
OK, I think the problem was that I had autostart set to TRUE, but was defining the `.on('open'...)` in another function, and the socket had already started so I suspect my function hadn't been bound to the socket and was causing some error.
By disabling the auto start, and calling `ws.open()` in the function where i defined the `open` bind, it all works now.

Hopefully this helps someone

**Comment by f3rno** [comment]
@amlwwalker ah, that makes sense :) I'm glad you resolved it!
