### ISSUE TITLE
not enougth info passed to events

### ISSUE THREAD

**Issue by skazska** [bitfinexcom/bitfinex-api-node#164]
this.emit('orderbook', event.symbol, res)
...
this.emit('trade', event.symbol, res)
etc.
while there another values regarding channel are keept in event,  like "prec"  - a precision, which i would like to receive in my event handler

**Comment by skazska** [comment]
could it be extended like 
this.emit('orderbook', event.symbol, res, event)
?

**Comment by f3rno** [comment]
@skazska the channel parameters never change, and are returned once after subscribing. You can fetch the channel data from the `ws2.channelMap` key (by `chanId`), or via `getChannelData ({ chanId, channel, symbol, key })` in the upcoming 2.0.0-beta release.

Since it is static, it isn't included on the event. `prec` is also passed in when subscribing to an OB channel, so the client shouldn't need to receive it again.

**Comment by skazska** [comment]
@f3rno sure, but here 2 problems i see with that approach:
1. I can't subscribe to 2 precision of 1 pair on 1 instance:    

`        bfnx = new BFX(key, secret, opts).ws
         bfnx.on('open', () => {
            bfnx.on('orderbook', (pair, book) => {
               //FIXME prec or length is not available here in handler....
               //here handler can't know which chanel fired an orderbook event
            }
            bfnx.subscribeOrderBook('tBTCUSD', 'P0', '25')
            bfnx.subscribeOrderBook('tBTCUSD', 'P1', '25')
        
         })
`
actually after that bitfinex-api-node/ws2.js  subscrubed to 2 chanels and firing events for both subscriptions, but handler cannot distinguish them...  
so there is a limitation forcing me to create new instance for every precision of 1 pair i want   which in turn means that i have to implement my own channels manager instead of getting benefit of yours  eliminating most of value of this library
