### ISSUE TITLE
Example: Update existing order via websocket

### ISSUE THREAD

**Issue by Anthbs** [bitfinexcom/bitfinex-api-node#185]
Can we get an example of updating an existing order via the websocket api?

I have tried to generate a request using the following format but it doesn't seem to work:
```
public generateUpdateOrderRequest(order: IOrder, price?: number, amount?: number) {
    return [
        0,
        'ou',
        null,
        {
            'id': order.id,
            'type': order.type,
            'amount': (amount || order.amount).toString(),
            'price': (price || order.price).toString(),
        }
    ];
}
```

**Comment by f3rno** [comment]
@Anthbs good idea! I will add another example soon, in the meantime you can check https://github.com/bitfinexcom/bitfinex-api-node/blob/master/lib/models/order.js#L95

Orders need to be re-created and cannot be updated in place.

**Comment by Anthbs** [comment]
Thanks that's how I currently work around it to just thought there might have been a better way.

**Comment by serzhiio** [comment]
Update(replace) orders feature is a must. Developers please implement it ASAP.
And why not to use immediate balance update after order executed?

**Comment by f3rno** [comment]
@serzhiio for performance reasons balance calculations are deferred and processed outside of the trading engine. This is also why orders are immutable, and must be re-created. It's a design decision, and something the API works with by offering a `recreate()` method :)

**Comment by serzhiio** [comment]
@f3rno so, i cant do anything with a design desicion, but order replacement system looks very slow.
Even if i decide to hold x3 funds on each side i'm still facing with huge delays because of big order canceling timings. And that thing cause possibility to execute two or more orders which even should not already exist. So if i get along with one problem there is other to be next.
How to deal with that? How is it possible to market making with such problems? So big exchange and so bad behaivior i cant understand that.

**Comment by serzhiio** [comment]
@f3rno very often it takes too long to cancel order and update wallet and сonsequently you miss the uptrend and get losses. Everything is simple. Cancel old+update wallet+create new. If at any of this points you get delay more than 500ms (BFX has more than 1s in fact) you loose. What can i say? 

P.S.: Even if i make reservation of balance on each side i still getting delays. Please report it to the stuff, thats vital thing for market maker. I have no such problems at Okex (And okex is a first exchange by the total trade volume).

**Comment by f3rno** [comment]
Closed by accident, re-opened.

@serzhiio I understand your problem, and will see what I can do about it. The delays you speak of can be avoided if you have sufficient balance to defer the balance calculation :) Of course, that is not optimal for our smaller clients, hence: I will speak with the backend team, and update this ticket with info.

**Comment by serzhiio** [comment]
I cant say i'm a small client. If i'm making $1M+ volume a day is it small?

20 февр. 2018 г. 11:40 пользователь "Cris Mihalache" <
notifications@github.com> написал:

Closed by accident, re-opened.

@serzhiio <https://github.com/serzhiio> I understand your problem, and will
see what I can do about it. The delays you speak of can be avoided if you
have sufficient balance to defer the balance calculation :) Of course, that
is not optimal for our smaller clients, hence: I will speak with the
backend team, and update this ticket with info.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bitfinexcom/bitfinex-api-node/issues/185#issuecomment-366904935>,
or mute the thread

**Comment by f3rno** [comment]
Fixed in `master`
