### ISSUE TITLE
Feature request: Buy or Sell available / max amount at market price

### ISSUE THREAD

**Issue by gsampathkumar** [bitfinexcom/bitfinex-api-node#289]
Is it possible to programmatically place an exchange market order that buys or sells whatever possible using all the available balance i.e. without having to specifiy a price or amount parameter to the new order API.

**Comment by f3rno** [comment]
@gsampathkumar this has been requested before, and unfortunately it is not possible. Instead, how about a way to quickly query the last-known-balance for a currency via the `WSv2` class?

**Comment by gsampathkumar** [comment]
That would work if the trade weren't going to fail because the balance was
deducted some commission. If that would never happen, what you recommend
would work.

**Comment by f3rno** [comment]
I'm closing this issue since it's out of scope for the node API; it is up to the user to first query data, and then make the relevant request. Due to the async nature of our trading platform, we cannot guarantee a balance calc as accurate for any period of time (since a trade may occur at any moment)
