### ISSUE TITLE
Re-subscribing doesn't work correctly

### ISSUE THREAD

**Issue by SiteBooster** [bitfinexcom/bitfinex-api-node#355]
When I subscribe a candle:
`ws.subscribeCandles(candle_key);`

Then unsubscribe that same candle:
`ws.unsubscribeCandles('t' + query.coin + 'USD', query.time)`

And then subscribe that candle again:
`ws.subscribeCandles(candle_key);`

I seem to get all candle data twice:
_[2018-6-26 01:07:49] Candle data for trade:1m:tXRPUSD:{
 "mts": 1529968020000,
 "open": 0.48054,
 "close": 0.48081,
 "high": 0.48082,
 "low": 0.48054,
 "volume": 3875.64068738
}
[2018-6-26 01:07:49] Candle data for trade:1m:tXRPUSD:{
 "mts": 1529968020000,
 "open": 0.48054,
 "close": 0.48081,
 "high": 0.48082,
 "low": 0.48054,
 "volume": 3875.64068738
}_

And when I repeat this process it adds a new set of candle data on each re-subscription.

Is this supposed to happen?

Thanks in advance!

**Comment by f3rno** [comment]
I tried to reproduce today and am unable to; there does seem to be a bug in managed candle handling, in that the latest candle from the managed set is not updated with the most recent candle update, but is updated immediately after & therefore available on the next tick.

Since the managed data functionality is being broken out into a plugin system now (and this bug has been in for some time), I will leave it unchanged. It is possible to receive 2 updates rapidly in succession from the server, but it has no relation to the number of subscriptions you have made in the past.
