### ISSUE TITLE
Questions about WS manager

### ISSUE THREAD

**Issue by tuloski** [bitfinexcom/bitfinex-api-node#413]
I have a few questions/doubts about the ws manager:

- If I have more than one WS because I pass the 250 limit, and give to the manager the key to authenticate, it seems both ws will authenticate. Intended or not?
- It's written that I can get the reference to a free ws using getFreeSocket, but that doesn't seem implemented.
- If I use getSocket() I get the ws state which atually doesn't include the ws itself, but only the pending subscriptions. Intended or not?

Overall it seems the ws manager wasn't completed at all.
In particular can anyone write a snippet to use the ws manager to both do the subscriptions and send orders? Because (idk why) the manager seems to not disconnect, while creating the normal WS2 it always disconnect and reconnect (maybe it's a problem with some parameters).

**Comment by tuloski** [comment]
PS: why the limit is 250 channels if the documentation says 50?

**Comment by f3rno** [comment]
@tuloski the limit was 250 before the change was rolled out, and was reduced shortly before release. I simply forgot to update constant, fixed by https://github.com/bitfinexcom/bitfinex-api-node/pull/415

The PR also fixes the mention of `getFreeSocket()`, as it is `getFreeDataSocket()`.

It is intended that all sockets are authenticated, but this may be changed as the manager is meant to be used for data channels only, and not for the auth channel. I am considering changing it.

`Because (idk why) the manager seems to not disconnect, while creating the normal WS2 it always disconnect and reconnect (maybe it's a problem with some parameters).` What do you mean by this? Nothing has changed with the standard `WSv2` class, I don't understand where the latest reconnect issues have come from.

**Comment by tuloski** [comment]
BTW even with 250 it wasn't complaining and no error were received.

**Comment by f3rno** [comment]
@tuloski where did you see a limit of 50 in the docs?

**Comment by tuloski** [comment]
https://www.bitfinex.com/posts/267
But actually it seems it's 250. Sorry for the confusion :(

**Comment by f3rno** [comment]
Yes I saw :see_no_evil: we did actually change it before release, I thought it had happened twice but no, 250 was the final one. I already reverted the commit.

I'll close this issue now, if you have more questions feel free to re-open
