### ISSUE TITLE
confusing documentation

### ISSUE THREAD

**Issue by npomfret** [bitfinexcom/bitfinex-api-node#465]
I can't get the authenticated websocket API to work if I follow the docs of the main README.md. The examples provided seem to handle the _auth_ process differently.  

The docs say:

```
const ws = bfx.ws()

ws.on('error', (err) => console.log(err))
ws.on('open', ws.auth.bind(ws))
ws.once('auth', () => {
  ...
})
```
... which doesn't appear to work - _auth_ never gets called.

But the [examples](https://github.com/bitfinexcom/bitfinex-api-node/blob/master/examples/ws2/auth.js) do it like this:

```
const ws = bfx.ws(2)

ws.on('open', () => { // wait for socket open
  ws.auth() // & authenticate
})

ws.once('auth', () => {
  debug('authenticated')
})

// Open the websocket connection
ws.open()
```

Which does work, for a while, but then results lots of errors:

    { event: 'error', msg: 'auth: dup', code: 10100 }

... and eventually 

    Error: auth failed: rate: limit (FAILED)

**Comment by f3rno** [comment]
> ... which doesn't appear to work - auth never gets called.

You need to call `ws.open()`

As for the duplicate auth error, it could be due to the connection resetting and the internal logic automatically re-authenticating; since the example binds with `.on` (i.e. `ws.on('open', () => ...` it will redundantly try to authenticate after every connection open). If using auto reconnect (which I assume here), you should change it to only auth once after the initial open by using `ws.once('open', () => ...`

**Comment by npomfret** [comment]
As for the duplicate auth error, I think it was reconnecting every 10 seconds, which is what was causing the rate limit error.   I've not looked into it in detail yet...
