### ISSUE TITLE
`fcs` not received if there are no funding credits when subscribing

### ISSUE THREAD

**Issue by dutu** [bitfinexcom/bitfinex-api-node#508]
#### Issue type
- [x] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description

`fcs` (funding credit snapshot) is not received (with empty array) if there are no funding credits when subscribing.
`fcn` is then received when new funding credits are then sent for new funding credits on the account, but `fcs` is never received.

This seems to be an issue with the Bitfinex backend server rather than with this module.

#### Steps to reproduce
- Subscribe to account information channel to keep track of funding credits, when there is no funding credit. 

#### Additional Notes:
-

**Comment by JacobPlaster** [comment]
Hey Dutu! Just to clear up some confusion - you dont have any funding credits open/active but you still expect to receive an empty funding credit snapshot?

This isnt a bug since we only send data down the websocket that we absolutely have to (for bandwidth reasons).

Correct me if wrong and I will re-open this.
