### ISSUE TITLE
walletsHistory does not return "available balance" and correct data

### ISSUE THREAD

**Issue by Benvaulter** [bitfinexcom/bitfinex-api-node#527]
#### Issue type
- [x] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
Whenever I call the wallet history endpoint, "balanceAvailable" is always null. Furthermore, it seems that for "empty" wallets, the data for the last change is returned. I do receive balance values for exchange and margin wallet, allthough they are empty - however, the mtsUpdate also references to some older time which is not the "end" query param I specified.

#### Steps to reproduce
Simply call the endpoint with "end" specified to now() or like 5mins in the past and compare result to actual balances as they appear when you log on to bitfinex.

##### Additional Notes:
-

**Comment by JacobPlaster** [comment]
Hi @Benvaulter. Firstly, the balance history endpoint is `v1` and we encourage users to move to `v2`. 

The calculation to infer your available balance is quite a resource heavy once, since it requires historical prices for each currency at different times. For this reason we dont provide the available balance. In order to obtain your available balance (like how our UI does it) you will have to subscribe to our websocket and use the `calc` flag, this will provide your available balance in realtime.
