### ISSUE TITLE
order_status returns 404

### ISSUE THREAD

**Issue by moeadham** [bitfinexcom/bitfinex-api-node#8]
I can see in your test that order_status was returning 404 for some time now.

Is this going to be resolved?
https://github.com/bitfinexcom/bitfinex-api-node/blob/master/test/rest-test.js#L236

**Comment by joshuarossi** [comment]
order status is the status of an order...if there is no order, then it will not be found (404) the test is ensuring that it is behaving as expected

you can see in the later tests that i check the incoming array to ensure it is empty.

in order to send an order, you would have to have money in the account, meaning that it could not be automated via travis, etc

**Comment by joshuarossi** [comment]
if i look for an order with ID 123, i get this:
`[Error: 404] `

if i look for an order which does exist, like 598091831, i get this:

```
{ id: 598091831,
  symbol: 'btcusd',
  exchange: null,
  price: '1.0',
  avg_execution_price: '0.0',
  side: 'buy',
  type: 'exchange limit',
  timestamp: '1453864412.0',
  is_live: true,
  is_cancelled: false,
  is_hidden: false,
  oco_order: null,
  was_forced: false,
  original_amount: '0.01',
  remaining_amount: '0.01',
  executed_amount: '0.0' }
```
